package run

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"

	"boundlane/agents"
	"boundlane/compiler"
	"boundlane/policies"
)

// ProjectFile is the optional policy file in a project root.
const ProjectFile = "boundlane.yaml"

// Resolved is the policy a run uses on the Free plan.
type Resolved struct {
	Doc          *compiler.Document
	Sources      string
	TeamRevision int
}

// ResolveFree layers ./boundlane.yaml (or the file given) over developer-default.
func ResolveFree(repo, file string) (Resolved, error) {
	base := policies.DeveloperDefault()
	if file == "" {
		file = filepath.Join(repo, ProjectFile)
		if _, err := os.Stat(file); errors.Is(err, fs.ErrNotExist) {
			return Resolved{Doc: base, Sources: "developer-default (built in)"}, nil
		}
	}
	raw, err := os.ReadFile(file)
	if err != nil {
		return Resolved{}, err
	}
	project, err := compiler.Parse(raw)
	if err != nil {
		return Resolved{}, fmt.Errorf("%s: %w", file, err)
	}
	merged, err := compiler.Merge(base, project)
	if err != nil {
		return Resolved{}, fmt.Errorf("%s: %w", file, err)
	}
	return Resolved{Doc: merged, Sources: "developer-default (built in) + " + relTo(repo, file)}, nil
}

// Compiled is a candidate and boundary written to disk for openshell and the prover.
type Compiled struct {
	Policy   string
	Boundary string
	Revision string
}

// WriteCompiled compiles doc for an agent and writes policy.yaml and boundary.yaml into dir.
func WriteCompiled(doc *compiler.Document, agent agents.Entry, dir, source string) (Compiled, error) {
	target := compiler.Target{Agent: agent.CompilerAgent(), Workdir: compiler.DefaultWorkdir}
	p, err := compiler.Compile(doc, target)
	if err != nil {
		return Compiled{}, err
	}
	b, err := compiler.Boundary(doc, target)
	if err != nil {
		return Compiled{}, err
	}
	pol, err := p.YAML("Generated by boundlane from " + source + " for " + agent.Name + ". Do not edit.")
	if err != nil {
		return Compiled{}, err
	}
	bnd, err := b.YAML("Boundary generated by boundlane from " + source + " for " + agent.Name + ". Do not edit.")
	if err != nil {
		return Compiled{}, err
	}
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return Compiled{}, err
	}
	c := Compiled{Policy: filepath.Join(dir, "policy.yaml"), Boundary: filepath.Join(dir, "boundary.yaml")}
	if err := os.WriteFile(c.Policy, pol, 0o600); err != nil {
		return Compiled{}, err
	}
	if err := os.WriteFile(c.Boundary, bnd, 0o600); err != nil {
		return Compiled{}, err
	}
	sum := sha256.Sum256(pol)
	c.Revision = "local-" + hex.EncodeToString(sum[:])[:8]
	return c, nil
}

func relTo(base, p string) string {
	if r, err := filepath.Rel(base, p); err == nil && !filepath.IsAbs(r) && r != "" && r[0] != '.' {
		return "./" + r
	}
	return p
}
