package compiler

import (
	"bytes"
	"errors"
	"flag"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

var update = flag.Bool("update", false, "rewrite golden files")

var claude = Agent{
	Name:     "claude",
	Binaries: []string{"/usr/local/lib/node_modules/@anthropic-ai/claude-code/bin/claude.exe"},
	Model:    []ModelEndpoint{{Host: "api.anthropic.com", Port: 443}},
}

func load(t *testing.T, name string) *Document {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", name))
	if err != nil {
		t.Fatal(err)
	}
	d, err := Parse(raw)
	if err != nil {
		t.Fatal(err)
	}
	return d
}

func golden(t *testing.T, name string, got []byte) {
	t.Helper()
	path := filepath.Join("testdata", "golden", name)
	if *update {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, got, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("%v (run go test ./compiler -update)", err)
	}
	if !bytes.Equal(got, want) {
		t.Errorf("%s differs from golden file\n--- got\n%s\n--- want\n%s", name, got, want)
	}
}

func TestGolden(t *testing.T) {
	base := load(t, "default.yaml")
	merged, err := Merge(base, load(t, "project.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	cases := map[string]*Document{
		"default": base,
		"project": merged,
		"review":  load(t, "review.yaml"),
	}
	for name, doc := range cases {
		t.Run(name, func(t *testing.T) {
			target := Target{Agent: claude}
			p, err := Compile(doc, target)
			if err != nil {
				t.Fatal(err)
			}
			out, err := p.YAML("Generated by boundlane from " + name + ". Do not edit.")
			if err != nil {
				t.Fatal(err)
			}
			golden(t, name+".policy.yaml", out)

			b, err := Boundary(doc, target)
			if err != nil {
				t.Fatal(err)
			}
			out, err = b.YAML("Boundary for " + name + ". Generated by boundlane. Do not edit.")
			if err != nil {
				t.Fatal(err)
			}
			golden(t, name+".boundary.yaml", out)
		})
	}
}

func TestCompileChoices(t *testing.T) {
	p, err := Compile(load(t, "default.yaml"), Target{Agent: claude})
	if err != nil {
		t.Fatal(err)
	}
	if p.FilesystemPolicy.IncludeWorkdir {
		t.Error("include_workdir must be false; the prover returns unsupported for workdir-dependent results")
	}
	if p.FilesystemPolicy.ReadWrite[0] != DefaultWorkdir {
		t.Errorf("workdir not listed first in read_write: %v", p.FilesystemPolicy.ReadWrite)
	}
	if p.Landlock.Compatibility != "hard_requirement" {
		t.Errorf("landlock = %q", p.Landlock.Compatibility)
	}
	for key, r := range p.NetworkPolicies {
		if strings.HasPrefix(key, "_provider_") {
			t.Errorf("rule key %q uses the reserved prefix", key)
		}
		for _, e := range r.Endpoints {
			if e.Protocol != "rest" || e.Enforcement != "enforce" {
				t.Errorf("%s: protocol=%q enforcement=%q; every endpoint must be enforced REST", key, e.Protocol, e.Enforcement)
			}
			if e.Access != "" && len(e.Rules) > 0 {
				t.Errorf("%s: an endpoint cannot combine access and rules", key)
			}
		}
	}
	for key, r := range p.NetworkPolicies {
		for _, e := range r.Endpoints {
			if e.AllowEncodedSlash {
				t.Errorf("%s: allow_encoded_slash makes prover 0.1.2 return unsupported", key)
			}
		}
	}
	for _, r := range p.NetworkPolicies {
		for _, e := range r.Endpoints {
			if e.Host == "api.anthropic.com" {
				t.Error("model API must come from the provider, not the candidate policy")
			}
		}
	}
}

func TestBoundaryRejectsModelHostInHosts(t *testing.T) {
	d := load(t, "default.yaml")
	d.Hosts = append(d.Hosts, Host{Host: "api.anthropic.com", Access: AccessReadOnly})
	if _, err := Boundary(d, Target{Agent: claude}); err == nil {
		t.Fatal("expected an error when the model API is also listed in hosts")
	}
}

func TestAgentHosts(t *testing.T) {
	a := claude
	a.Hosts = []AgentHost{{Host: "platform.claude.com"}}
	for name, build := range map[string]func(*Document, Target) (*Policy, error){"compile": Compile, "boundary": Boundary} {
		p, err := build(load(t, "default.yaml"), Target{Agent: a})
		if err != nil {
			t.Fatal(err)
		}
		r, ok := p.NetworkPolicies["platform_claude_com"]
		if !ok {
			t.Fatalf("%s: no rule for the agent host", name)
		}
		ep := r.Endpoints[0]
		if ep.Port != 443 || ep.Access != AccessReadOnly || ep.Protocol != "rest" || len(r.Binaries) != 1 || r.Binaries[0].Path != a.Binaries[0] {
			t.Errorf("%s: rule = %+v", name, r)
		}
	}

	d := load(t, "default.yaml")
	d.Hosts = append(d.Hosts, Host{Host: "platform.claude.com", Port: 443, Access: AccessReadWrite, Allow: []string{"POST /x"}})
	p, err := Compile(d, Target{Agent: a})
	if err != nil {
		t.Fatal(err)
	}
	if r := p.NetworkPolicies["platform_claude_com"]; r.Endpoints[0].Access == AccessReadOnly {
		t.Error("a host the document lists must keep the document's rule")
	}

	a.Hosts = []AgentHost{{Host: "api.anthropic.com"}}
	if _, err := Compile(load(t, "default.yaml"), Target{Agent: a}); err == nil {
		t.Error("an agent host that is also a model endpoint must be rejected")
	}
}

func TestRejects(t *testing.T) {
	cases := map[string]string{
		"version":            "version: 2\n",
		"auto approval":      "version: 1\napprovals: auto\n",
		"workspace":          "version: 1\nworkspace: full\n",
		"wildcard":           "version: 1\nhosts: [{host: '*.github.com', access: read-only}]\n",
		"ip":                 "version: 1\nhosts: [{host: 10.0.0.1, access: read-only}]\n",
		"scheme":             "version: 1\nhosts: [{host: 'https://api.github.com', access: read-only}]\n",
		"uppercase":          "version: 1\nhosts: [{host: API.github.com, access: read-only}]\n",
		"localhost":          "version: 1\nhosts: [{host: localhost, access: read-only}]\n",
		"gateway host":       "version: 1\nhosts: [{host: host.openshell.internal, access: read-only}]\n",
		"single label":       "version: 1\nhosts: [{host: intranet, access: read-only}]\n",
		"blocked port":       "version: 1\nhosts: [{host: k8s.example.com, port: 6443, access: read-only}]\n",
		"bad port":           "version: 1\nhosts: [{host: a.example.com, port: 70000, access: read-only}]\n",
		"duplicate host":     "version: 1\nhosts: [{host: a.example.com, access: read-only}, {host: a.example.com, port: 443, access: read-only}]\n",
		"full access":        "version: 1\nhosts: [{host: a.example.com, access: full}]\n",
		"rw without allow":   "version: 1\nhosts: [{host: a.example.com, access: read-write}]\n",
		"ro with allow":      "version: 1\nhosts: [{host: a.example.com, access: read-only, allow: ['GET /']}]\n",
		"any method":         "version: 1\nhosts: [{host: a.example.com, access: read-write, allow: ['* /x']}]\n",
		"query in path":      "version: 1\nhosts: [{host: a.example.com, access: read-write, allow: ['GET /x?y=1']}]\n",
		"relative path rule": "version: 1\nhosts: [{host: a.example.com, access: read-write, allow: ['GET x']}]\n",
		"home path":          "version: 1\npaths: {read_only: [/home/dana/.aws]}\n",
		"mac home path":      "version: 1\npaths: {read_only: [/Users/dana]}\n",
		"root home":          "version: 1\npaths: {read_only: [/root]}\n",
		"relative fs path":   "version: 1\npaths: {read_only: [opt/x]}\n",
		"dotdot":             "version: 1\npaths: {read_only: [/opt/../etc]}\n",
		"unclean":            "version: 1\npaths: {read_only: [/opt/x/]}\n",
		"writable root":      "version: 1\npaths: {read_write: [/]}\n",
		"path in both":       "version: 1\npaths: {read_only: [/opt/x], read_write: [/opt/x]}\n",
		"workdir as path":    "version: 1\npaths: {read_only: [/sandbox]}\n",
		"agent not allowed":  "version: 1\nagents: [codex]\n",
	}
	for name, src := range cases {
		t.Run(name, func(t *testing.T) {
			d, err := Parse([]byte(src))
			if err != nil {
				t.Fatalf("parse: %v", err)
			}
			if _, err := Compile(d, Target{Agent: claude}); err == nil {
				t.Fatal("expected Compile to reject this document")
			}
		})
	}
}

func TestParseRejectsUnknownFields(t *testing.T) {
	for name, src := range map[string]string{
		"unknown top level": "version: 1\nauto_approve: true\n",
		"unknown host key":  "version: 1\nhosts: [{host: a.example.com, access: read-only, tls: skip}]\n",
		"duplicate key":     "version: 1\nversion: 1\n",
		"two documents":     "version: 1\n---\nversion: 1\n",
	} {
		t.Run(name, func(t *testing.T) {
			if _, err := Parse([]byte(src)); err == nil {
				t.Fatal("expected a parse error")
			}
		})
	}
}

func TestRejectsGlobBinary(t *testing.T) {
	a := claude
	a.Binaries = []string{"/usr/bin/*"}
	if _, err := Compile(load(t, "default.yaml"), Target{Agent: a}); err == nil {
		t.Fatal("expected glob binaries to be rejected")
	}
}

func TestValidationListsEveryProblem(t *testing.T) {
	d, _ := Parse([]byte("version: 3\nworkspace: x\napprovals: auto\n"))
	err := d.Validate()
	var ve *ValidationError
	if !errors.As(err, &ve) || len(ve.Problems) != 3 {
		t.Fatalf("want 3 problems, got %v", err)
	}
}

func TestMerge(t *testing.T) {
	base := load(t, "default.yaml")
	merged, err := Merge(base, load(t, "project.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	var gh *Host
	for i := range merged.Hosts {
		if merged.Hosts[i].Host == "api.github.com" {
			gh = &merged.Hosts[i]
		}
	}
	if gh == nil || gh.Access != AccessReadWrite || len(gh.Allow) != 2 {
		t.Fatalf("project entry should replace the base entry for api.github.com, got %+v", gh)
	}
	if len(merged.Hosts) != 5 {
		t.Errorf("want 5 hosts after merge, got %d", len(merged.Hosts))
	}
	if base.Hosts[0].Access != AccessReadOnly {
		t.Error("Merge modified the base document")
	}

	for name, src := range map[string]string{
		"name":      "version: 1\nname: mine\n",
		"agents":    "version: 1\nagents: [claude]\n",
		"approvals": "version: 1\napprovals: auto\n",
	} {
		t.Run(name, func(t *testing.T) {
			p, _ := Parse([]byte(src))
			if _, err := Merge(base, p); err == nil {
				t.Fatalf("project file must not set %s", name)
			}
		})
	}
}

// The compiler must stay testable without a gateway: no process execution and
// no dependency on the CLI packages.
func TestNoGatewayDependency(t *testing.T) {
	files, _ := filepath.Glob("*.go")
	fset := token.NewFileSet()
	for _, f := range files {
		if strings.HasSuffix(f, "_test.go") {
			continue
		}
		parsed, err := parser.ParseFile(fset, f, nil, parser.ImportsOnly)
		if err != nil {
			t.Fatal(err)
		}
		for _, imp := range parsed.Imports {
			path, _ := strconv.Unquote(imp.Path.Value)
			if path == "os/exec" || strings.HasPrefix(path, "boundlane/") {
				t.Errorf("%s imports %s", f, path)
			}
		}
	}
}
